# Generated by Django 2.2 on 2019-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190416_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(default='profiles/default_profile.jpg', upload_to='profiles'),
        ),
    ]
