# Generated by Django 2.2 on 2019-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.ImageField(default='default_product.jpg', upload_to='profiles'),
        ),
    ]
