# Generated by Django 2.2 on 2019-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0003_auto_20190416_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.ImageField(default='default_product.jpg', upload_to='products'),
        ),
    ]
