# Generated by Django 2.2 on 2019-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0004_auto_20190416_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.ImageField(default='products/default_product.jpg', upload_to='products'),
        ),
    ]
