# Generated by Django 2.2 on 2019-04-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0007_errors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Errors',
            new_name='Error',
        ),
    ]
